#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Sylom")]
	public partial class DMZDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DMZDataContext() : 
				base(global::DAL.Properties.Settings.Default.SylomConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public DMZDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DMZDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DMZDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DMZDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.agregarRol")]
		public ISingleResult<agregarRolResult> agregarRol([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(75)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre);
			return ((ISingleResult<agregarRolResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.agregarRolApartado")]
		public int agregarRolApartado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idRol, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idApartado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> crear, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> leer, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> editar, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> eliminar)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idRol, idApartado, crear, leer, editar, eliminar);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.consultarRoles")]
		public ISingleResult<consultarRolesResult> consultarRoles([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario);
			return ((ISingleResult<consultarRolesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eliminarRol")]
		public int eliminarRol([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idRol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idRol);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eliminarRolApartado")]
		public int eliminarRolApartado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idRol, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idApartado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idRol, idApartado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.consultaLoginPermisos")]
		public ISingleResult<consultaLoginPermisosResult> consultaLoginPermisos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario);
			return ((ISingleResult<consultaLoginPermisosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.consultaLoginAuth")]
		public ISingleResult<consultaLoginAuthResult> consultaLoginAuth([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string contra)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario, contra);
			return ((ISingleResult<consultaLoginAuthResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.consultarApartados")]
		public ISingleResult<consultarApartadosResult> consultarApartados()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<consultarApartadosResult>)(result.ReturnValue));
		}
	}
	
	public partial class agregarRolResult
	{
		
		private int _idRol;
		
		public agregarRolResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRol", DbType="Int NOT NULL")]
		public int idRol
		{
			get
			{
				return this._idRol;
			}
			set
			{
				if ((this._idRol != value))
				{
					this._idRol = value;
				}
			}
		}
	}
	
	public partial class consultarRolesResult
	{
		
		private int _idRol;
		
		private string _descripcion;
		
		public consultarRolesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRol", DbType="Int NOT NULL")]
		public int idRol
		{
			get
			{
				return this._idRol;
			}
			set
			{
				if ((this._idRol != value))
				{
					this._idRol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(75)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
	}
	
	public partial class consultaLoginPermisosResult
	{
		
		private string _descripcion;
		
		private int _idApartado;
		
		private string _nombreApartado;
		
		private string _siteUrl;
		
		private string _icon;
		
		private System.Nullable<bool> _crear;
		
		private System.Nullable<bool> _leer;
		
		private System.Nullable<bool> _editar;
		
		private System.Nullable<bool> _eliminar;
		
		public consultaLoginPermisosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(75)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idApartado", DbType="Int NOT NULL")]
		public int idApartado
		{
			get
			{
				return this._idApartado;
			}
			set
			{
				if ((this._idApartado != value))
				{
					this._idApartado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreApartado", DbType="VarChar(25)")]
		public string nombreApartado
		{
			get
			{
				return this._nombreApartado;
			}
			set
			{
				if ((this._nombreApartado != value))
				{
					this._nombreApartado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteUrl", DbType="VarChar(200)")]
		public string siteUrl
		{
			get
			{
				return this._siteUrl;
			}
			set
			{
				if ((this._siteUrl != value))
				{
					this._siteUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_icon", DbType="VarChar(200)")]
		public string icon
		{
			get
			{
				return this._icon;
			}
			set
			{
				if ((this._icon != value))
				{
					this._icon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_crear", DbType="Bit")]
		public System.Nullable<bool> crear
		{
			get
			{
				return this._crear;
			}
			set
			{
				if ((this._crear != value))
				{
					this._crear = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_leer", DbType="Bit")]
		public System.Nullable<bool> leer
		{
			get
			{
				return this._leer;
			}
			set
			{
				if ((this._leer != value))
				{
					this._leer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_editar", DbType="Bit")]
		public System.Nullable<bool> editar
		{
			get
			{
				return this._editar;
			}
			set
			{
				if ((this._editar != value))
				{
					this._editar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eliminar", DbType="Bit")]
		public System.Nullable<bool> eliminar
		{
			get
			{
				return this._eliminar;
			}
			set
			{
				if ((this._eliminar != value))
				{
					this._eliminar = value;
				}
			}
		}
	}
	
	public partial class consultaLoginAuthResult
	{
		
		private string _cedula;
		
		private string _nombre;
		
		private string _apellido1;
		
		private string _apellido2;
		
		private string _direccion2;
		
		private string _provincia;
		
		private string _canton;
		
		private string _distrito;
		
		private int _genero;
		
		private System.Nullable<System.DateTime> _fechaNacimiento;
		
		private int _idEmpleado;
		
		private System.Nullable<decimal> _salario;
		
		private int _idTipoEmpleado;
		
		private string _descripcion;
		
		private int _idUsuario;
		
		public consultaLoginAuthResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string cedula
		{
			get
			{
				return this._cedula;
			}
			set
			{
				if ((this._cedula != value))
				{
					this._cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido1", DbType="VarChar(30)")]
		public string apellido1
		{
			get
			{
				return this._apellido1;
			}
			set
			{
				if ((this._apellido1 != value))
				{
					this._apellido1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido2", DbType="VarChar(30)")]
		public string apellido2
		{
			get
			{
				return this._apellido2;
			}
			set
			{
				if ((this._apellido2 != value))
				{
					this._apellido2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion2", DbType="VarChar(255)")]
		public string direccion2
		{
			get
			{
				return this._direccion2;
			}
			set
			{
				if ((this._direccion2 != value))
				{
					this._direccion2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_provincia", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string provincia
		{
			get
			{
				return this._provincia;
			}
			set
			{
				if ((this._provincia != value))
				{
					this._provincia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_canton", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string canton
		{
			get
			{
				return this._canton;
			}
			set
			{
				if ((this._canton != value))
				{
					this._canton = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_distrito", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string distrito
		{
			get
			{
				return this._distrito;
			}
			set
			{
				if ((this._distrito != value))
				{
					this._distrito = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_genero", DbType="Int NOT NULL")]
		public int genero
		{
			get
			{
				return this._genero;
			}
			set
			{
				if ((this._genero != value))
				{
					this._genero = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaNacimiento", DbType="Date")]
		public System.Nullable<System.DateTime> fechaNacimiento
		{
			get
			{
				return this._fechaNacimiento;
			}
			set
			{
				if ((this._fechaNacimiento != value))
				{
					this._fechaNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmpleado", DbType="Int NOT NULL")]
		public int idEmpleado
		{
			get
			{
				return this._idEmpleado;
			}
			set
			{
				if ((this._idEmpleado != value))
				{
					this._idEmpleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salario", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> salario
		{
			get
			{
				return this._salario;
			}
			set
			{
				if ((this._salario != value))
				{
					this._salario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoEmpleado", DbType="Int NOT NULL")]
		public int idTipoEmpleado
		{
			get
			{
				return this._idTipoEmpleado;
			}
			set
			{
				if ((this._idTipoEmpleado != value))
				{
					this._idTipoEmpleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(75) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL")]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this._idUsuario = value;
				}
			}
		}
	}
	
	public partial class consultarApartadosResult
	{
		
		private int _idApartado;
		
		private string _nombreApartado;
		
		public consultarApartadosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idApartado", DbType="Int NOT NULL")]
		public int idApartado
		{
			get
			{
				return this._idApartado;
			}
			set
			{
				if ((this._idApartado != value))
				{
					this._idApartado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreApartado", DbType="VarChar(25)")]
		public string nombreApartado
		{
			get
			{
				return this._nombreApartado;
			}
			set
			{
				if ((this._nombreApartado != value))
				{
					this._nombreApartado = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
