<?xml version="1.0" encoding="utf-8"?><Database Name="Sylom" Class="DMZDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=server.com;Initial Catalog=Sylom;Persist Security Info=True;User ID=usercyc" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="SylomConnectionString2" Provider="System.Data.SqlClient" />
  <Function Name="dbo.agregarRol" Method="agregarRol">
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(75)" />
    <ElementType Name="agregarRolResult">
      <Column Name="idRol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.agregarRolApartado" Method="agregarRolApartado">
    <Parameter Name="idRol" Type="System.Int32" DbType="Int" />
    <Parameter Name="idApartado" Type="System.Int32" DbType="Int" />
    <Parameter Name="crear" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="leer" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="editar" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="eliminar" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.consultarRoles" Method="consultarRoles">
    <Parameter Name="idUsuario" Type="System.Int32" DbType="Int" />
    <ElementType Name="consultarRolesResult">
      <Column Name="idRol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(75)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.eliminarRol" Method="eliminarRol">
    <Parameter Name="idRol" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.consultaLoginPermisos" Method="consultaLoginPermisos">
    <Parameter Name="idUsuario" Type="System.Int32" DbType="Int" />
    <ElementType Name="consultaLoginPermisosResult">
      <Column Name="descripcion" Type="System.String" DbType="VarChar(75)" CanBeNull="true" />
      <Column Name="idApartado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombreApartado" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="siteUrl" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="icon" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="crear" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="leer" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="editar" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="eliminar" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.consultarApartados" Method="consultarApartados">
    <ElementType Name="consultarApartadosResult">
      <Column Name="idApartado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombreApartado" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.consultarUsuarios" Method="consultarUsuarios">
    <ElementType Name="consultarUsuariosResult">
      <Column Name="nombre" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.consultaLoginAuth" Method="consultaLoginAuth">
    <Parameter Name="usuario" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="contra" Type="System.String" DbType="VarChar(255)" />
    <ElementType Name="consultaLoginAuthResult">
      <Column Name="nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="idEmpleado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idTipoEmpleado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(75) NOT NULL" CanBeNull="false" />
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.agregarRolUsuario" Method="agregarRolUsuario">
    <Parameter Name="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="idRol" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.consultarRolApartados" Method="consultarRolApartados">
    <Parameter Name="idRol" Type="System.Int32" DbType="Int" />
    <ElementType Name="consultarRolApartadosResult">
      <Column Name="idRol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(75)" CanBeNull="true" />
      <Column Name="idRol1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idApartado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="crear" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="leer" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="editar" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="eliminar" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="idApartado1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombreApartado" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="siteUrl" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="icon" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.consultarRolUsuarios" Method="consultarRolUsuarios">
    <Parameter Name="idRol" Type="System.Int32" DbType="Int" />
    <ElementType Name="consultarRolUsuariosResult">
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.actualizarRol" Method="actualizarRol">
    <Parameter Name="idRol" Type="System.Int32" DbType="Int" />
    <Parameter Name="descripcion" Type="System.String" DbType="VarChar(75)" />
    <Return Type="System.Int32" />
  </Function>
</Database>