#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Sylom")]
	public partial class LQBitacoraDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public LQBitacoraDataContext() : 
				base(global::DAL.Properties.Settings.Default.SylomConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public LQBitacoraDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LQBitacoraDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LQBitacoraDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LQBitacoraDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.agregarRegistroBitacora")]
		public int agregarRegistroBitacora([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(75)")] string controlador, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(75)")] string metodo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string msj, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> tipo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), controlador, metodo, msj, tipo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.verRegistroBitacora")]
		public List<verRegistroBitacoraResult> verRegistroBitacora()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((List<verRegistroBitacoraResult>)(result.ReturnValue));
		}
	}
	
	public partial class verRegistroBitacoraResult
	{
		
		private int _idBitacora;
		
		private string _controlador;
		
		private string _metodo;
		
		private string _msj;
		
		private System.DateTime _fecha;
		
		private char _tipo;
		
		public verRegistroBitacoraResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idBitacora", DbType="Int NOT NULL")]
		public int idBitacora
		{
			get
			{
				return this._idBitacora;
			}
			set
			{
				if ((this._idBitacora != value))
				{
					this._idBitacora = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_controlador", DbType="VarChar(75) NOT NULL", CanBeNull=false)]
		public string controlador
		{
			get
			{
				return this._controlador;
			}
			set
			{
				if ((this._controlador != value))
				{
					this._controlador = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_metodo", DbType="VarChar(75) NOT NULL", CanBeNull=false)]
		public string metodo
		{
			get
			{
				return this._metodo;
			}
			set
			{
				if ((this._metodo != value))
				{
					this._metodo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msj", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string msj
		{
			get
			{
				return this._msj;
			}
			set
			{
				if ((this._msj != value))
				{
					this._msj = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date NOT NULL")]
		public System.DateTime fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this._fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="Char(1) NOT NULL")]
		public char tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this._tipo = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
