<?xml version="1.0" encoding="utf-8"?><Database Name="Sylom" Class="LQCargaArchivoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=server.com;Initial Catalog=Sylom;User ID=usercyc" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="SylomConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.consultaPersona" Method="consultaPersona">
    <Parameter Name="cedula" Type="System.String" DbType="VarChar(15)" />
    <ElementType Name="consultaPersonaResult">
      <Column Name="idPersona" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cedula" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="apellido1" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="apellido2" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="direccionPadron" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="direccion2" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="provincia" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="canton" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="distrito" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="genero" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fechaNacimiento" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="edad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="lastUpdate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="activo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.manejoActivos" Method="manejoActivos">
    <Parameter Name="cedula" Type="System.String" DbType="VarChar(15)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.mantenimientoPersonas" Method="mantenimientoPersonas">
    <Parameter Name="cedula" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="apellido1" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="apellido2" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="direccionPadron" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="direccion2" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="provincia" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="canton" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="distrito" Type="System.String" DbType="VarChar(3)" />
    <Parameter Name="genero" Type="System.Int32" DbType="Int" />
    <Parameter Name="fechaNacimiento" Type="System.DateTime" DbType="Date" />
    <Parameter Name="edad" Type="System.Int32" DbType="Int" />
    <Parameter Name="email" Type="System.String" DbType="VarChar(300)" />
    <Parameter Name="telefono" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="activo" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
</Database>