<?xml version="1.0" encoding="utf-8"?><Database Name="Sylom" Class="LQMantenimientosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=server.com;Initial Catalog=Sylom;Persist Security Info=True;User ID=usercyc" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="SylomConnectionString2" Provider="System.Data.SqlClient" />
  <Function Name="dbo.actualizarMedicina" Method="actualizarMedicina">
    <Parameter Name="nombreMedicina" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="idMedicina" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.actualizarTipoEmpleado" Method="actualizarTipoEmpleado">
    <Parameter Name="nombreTipoEmpleado" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="idTipoEmpleado" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.actualizarTipoPaciente" Method="actualizarTipoPaciente">
    <Parameter Name="nombreTipoPaciente" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="idTipoPaciente" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.agregarMedicina" Method="agregarMedicina">
    <Parameter Name="nombreMedicina" Type="System.String" DbType="VarChar(15)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.agregarTipoEmpleado" Method="agregarTipoEmpleado">
    <Parameter Name="nombreTipoEmpleado" Type="System.String" DbType="VarChar(15)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.agregarTipoPaciente" Method="agregarTipoPaciente">
    <Parameter Name="nombreTipoPaciente" Type="System.String" DbType="VarChar(15)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.eliminarMedicina" Method="eliminarMedicina">
    <Parameter Name="idMedicina" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.eliminarTipoEmpleado" Method="eliminarTipoEmpleado">
    <Parameter Name="idTipoEmpleado" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.eliminarTipoPaciente" Method="eliminarTipoPaciente">
    <Parameter Name="idTipoPaciente" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.obtenerMedicinas" Method="obtenerMedicinas">
    <ElementType Name="obtenerMedicinasResult">
      <Column Name="idMedicina" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(75) NOT NULL" CanBeNull="false" />
      <Column Name="activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.obtenerTipoPacientes" Method="obtenerTipoPacientes">
    <ElementType Name="obtenerTipoPacientesResult">
      <Column Name="idTipoPaciente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.verficicarUsuarioEmpleado" Method="verficicarUsuarioEmpleado">
    <Parameter Name="idEmpleado" Type="System.Int32" DbType="Int" />
    <Parameter Name="contra" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="output" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.actualizarInstitucion" Method="actualizarInstitucion">
    <Parameter Name="nombreInstitucion" Type="System.String" DbType="VarChar(75)" />
    <Parameter Name="direccion" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="telefono" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="idInstitucion" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.agregarInstitucion" Method="agregarInstitucion">
    <Parameter Name="nombreInstitucion" Type="System.String" DbType="VarChar(75)" />
    <Parameter Name="direccion" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="telefono" Type="System.String" DbType="VarChar(15)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.eliminarInstitucion" Method="eliminarInstitucion">
    <Parameter Name="idInstitucion" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.obtenerInstituciones" Method="obtenerInstituciones">
    <ElementType Name="obtenerInstitucionesResult">
      <Column Name="idInstitucion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombreInstitucion" Type="System.String" DbType="VarChar(75)" CanBeNull="true" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.obtenerInstitucion" Method="obtenerInstitucion">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="obtenerInstitucionResult">
      <Column Name="idInstitucion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombreInstitucion" Type="System.String" DbType="VarChar(75)" CanBeNull="true" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.obtenerMedicina" Method="obtenerMedicina">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="obtenerMedicinaResult">
      <Column Name="idMedicina" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(75) NOT NULL" CanBeNull="false" />
      <Column Name="activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.obtenerTipoEmpleado" Method="obtenerTipoEmpleado">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="obtenerTipoEmpleadoResult">
      <Column Name="idTipoEmpleado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(75) NOT NULL" CanBeNull="false" />
      <Column Name="activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.obtenerTipoPaciente" Method="obtenerTipoPaciente">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="obtenerTipoPacienteResult">
      <Column Name="idTipoPaciente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.obtenerTipoEmpleados" Method="obtenerTipoEmpleados">
    <Parameter Name="idEmpleado" Type="System.Int32" DbType="Int" />
    <ElementType Name="obtenerTipoEmpleadosResult">
      <Column Name="idTipoEmpleado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(75) NOT NULL" CanBeNull="false" />
      <Column Name="asignado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>