#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Sylom")]
	public partial class LQProcesosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public LQProcesosDataContext() : 
				base(global::DAL.Properties.Settings.Default.SylomConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public LQProcesosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LQProcesosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LQProcesosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LQProcesosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.agregarPaciente")]
		public int agregarPaciente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string apellido1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string apellido2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string direccion2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1)")] string provincia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2)")] string canton, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(3)")] string distrito, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> genero, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string fechaNacimiento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(250)")] string descripcionCliente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTipoPaciente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idInstitucion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(350)")] string descripcionExpediente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula, nombre, apellido1, apellido2, direccion2, provincia, canton, distrito, genero, fechaNacimiento, descripcionCliente, idTipoPaciente, idInstitucion, descripcionExpediente);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eliminarPaciente")]
		public int eliminarPaciente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPaciente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPaciente);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.actualizarPaciente")]
		public int actualizarPaciente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPaciente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string apellido1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string apellido2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string direccion2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1)")] string provincia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2)")] string canton, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(3)")] string distrito, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> genero, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string fechaNacimiento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(250)")] string descripcionCliente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTipoPaciente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idInstitucion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(350)")] string descripcionExpediente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPaciente, cedula, nombre, apellido1, apellido2, direccion2, provincia, canton, distrito, genero, fechaNacimiento, descripcionCliente, idTipoPaciente, idInstitucion, descripcionExpediente);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.obtenerPacientes")]
		public ISingleResult<obtenerPacientesResult> obtenerPacientes()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<obtenerPacientesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.consultarProvincias")]
		public ISingleResult<consultarProvinciasResult> consultarProvincias()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<consultarProvinciasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.consultarCantones")]
		public ISingleResult<consultarCantonesResult> consultarCantones([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1)")] string idProvincia)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProvincia);
			return ((ISingleResult<consultarCantonesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.consultarDistritos")]
		public ISingleResult<consultarDistritosResult> consultarDistritos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1)")] string idProvincia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2)")] string idCanton)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProvincia, idCanton);
			return ((ISingleResult<consultarDistritosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.obtenerPaciente")]
		public ISingleResult<obtenerPacienteResult> obtenerPaciente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPaciente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPaciente);
			return ((ISingleResult<obtenerPacienteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cancelarSesion")]
		public int cancelarSesion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idSesion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idSesion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.agregarSesion")]
		public int agregarSesion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(55)")] string asunto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(11)")] string fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(7)")] string hora, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string notas, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string sintomas, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idExpediente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), asunto, fecha, hora, notas, sintomas, idExpediente, idUsuario);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.consultaSesiones")]
		public ISingleResult<consultaSesionesResult> consultaSesiones()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<consultaSesionesResult>)(result.ReturnValue));
		}
	}
	
	public partial class obtenerPacientesResult
	{
		
		private int _idPaciente;
		
		private string _cedula;
		
		private string _nombre;
		
		private string _apellido1;
		
		private string _apellido2;
		
		private string _provincia;
		
		private string _canton;
		
		private string _distrito;
		
		private string _fechaNacimiento;
		
		private string _descripcionPaciente;
		
		private int _idTipoPaciente;
		
		private int _idInstitucion;
		
		private string _descripcionExpediente;
		
		public obtenerPacientesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPaciente", DbType="Int NOT NULL")]
		public int idPaciente
		{
			get
			{
				return this._idPaciente;
			}
			set
			{
				if ((this._idPaciente != value))
				{
					this._idPaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string cedula
		{
			get
			{
				return this._cedula;
			}
			set
			{
				if ((this._cedula != value))
				{
					this._cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido1", DbType="VarChar(30)")]
		public string apellido1
		{
			get
			{
				return this._apellido1;
			}
			set
			{
				if ((this._apellido1 != value))
				{
					this._apellido1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido2", DbType="VarChar(30)")]
		public string apellido2
		{
			get
			{
				return this._apellido2;
			}
			set
			{
				if ((this._apellido2 != value))
				{
					this._apellido2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_provincia", DbType="VarChar(1)")]
		public string provincia
		{
			get
			{
				return this._provincia;
			}
			set
			{
				if ((this._provincia != value))
				{
					this._provincia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_canton", DbType="VarChar(2)")]
		public string canton
		{
			get
			{
				return this._canton;
			}
			set
			{
				if ((this._canton != value))
				{
					this._canton = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_distrito", DbType="VarChar(3)")]
		public string distrito
		{
			get
			{
				return this._distrito;
			}
			set
			{
				if ((this._distrito != value))
				{
					this._distrito = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaNacimiento", DbType="VarChar(30)")]
		public string fechaNacimiento
		{
			get
			{
				return this._fechaNacimiento;
			}
			set
			{
				if ((this._fechaNacimiento != value))
				{
					this._fechaNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcionPaciente", DbType="VarChar(250)")]
		public string descripcionPaciente
		{
			get
			{
				return this._descripcionPaciente;
			}
			set
			{
				if ((this._descripcionPaciente != value))
				{
					this._descripcionPaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoPaciente", DbType="Int NOT NULL")]
		public int idTipoPaciente
		{
			get
			{
				return this._idTipoPaciente;
			}
			set
			{
				if ((this._idTipoPaciente != value))
				{
					this._idTipoPaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idInstitucion", DbType="Int NOT NULL")]
		public int idInstitucion
		{
			get
			{
				return this._idInstitucion;
			}
			set
			{
				if ((this._idInstitucion != value))
				{
					this._idInstitucion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcionExpediente", DbType="VarChar(350) NOT NULL", CanBeNull=false)]
		public string descripcionExpediente
		{
			get
			{
				return this._descripcionExpediente;
			}
			set
			{
				if ((this._descripcionExpediente != value))
				{
					this._descripcionExpediente = value;
				}
			}
		}
	}
	
	public partial class consultarProvinciasResult
	{
		
		private string _idProvincia;
		
		private string _nombre;
		
		public consultarProvinciasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProvincia", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string idProvincia
		{
			get
			{
				return this._idProvincia;
			}
			set
			{
				if ((this._idProvincia != value))
				{
					this._idProvincia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(15)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
	}
	
	public partial class consultarCantonesResult
	{
		
		private string _idCanton;
		
		private string _nombre;
		
		private string _idProvincia;
		
		public consultarCantonesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCanton", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string idCanton
		{
			get
			{
				return this._idCanton;
			}
			set
			{
				if ((this._idCanton != value))
				{
					this._idCanton = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(15)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProvincia", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string idProvincia
		{
			get
			{
				return this._idProvincia;
			}
			set
			{
				if ((this._idProvincia != value))
				{
					this._idProvincia = value;
				}
			}
		}
	}
	
	public partial class consultarDistritosResult
	{
		
		private string _idDistrito;
		
		private string _nombre;
		
		private string _idProvincia;
		
		private string _idCanton;
		
		public consultarDistritosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDistrito", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string idDistrito
		{
			get
			{
				return this._idDistrito;
			}
			set
			{
				if ((this._idDistrito != value))
				{
					this._idDistrito = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProvincia", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string idProvincia
		{
			get
			{
				return this._idProvincia;
			}
			set
			{
				if ((this._idProvincia != value))
				{
					this._idProvincia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCanton", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string idCanton
		{
			get
			{
				return this._idCanton;
			}
			set
			{
				if ((this._idCanton != value))
				{
					this._idCanton = value;
				}
			}
		}
	}
	
	public partial class obtenerPacienteResult
	{
		
		private int _idPaciente;
		
		private string _direccion2;
		
		private int _genero;
		
		private string _cedula;
		
		private string _nombre;
		
		private string _apellido1;
		
		private string _apellido2;
		
		private string _provincia;
		
		private string _canton;
		
		private string _distrito;
		
		private string _fechaNacimiento;
		
		private string _descripcionPaciente;
		
		private int _idTipoPaciente;
		
		private int _idInstitucion;
		
		private string _descripcionExpediente;
		
		public obtenerPacienteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPaciente", DbType="Int NOT NULL")]
		public int idPaciente
		{
			get
			{
				return this._idPaciente;
			}
			set
			{
				if ((this._idPaciente != value))
				{
					this._idPaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion2", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string direccion2
		{
			get
			{
				return this._direccion2;
			}
			set
			{
				if ((this._direccion2 != value))
				{
					this._direccion2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_genero", DbType="Int NOT NULL")]
		public int genero
		{
			get
			{
				return this._genero;
			}
			set
			{
				if ((this._genero != value))
				{
					this._genero = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string cedula
		{
			get
			{
				return this._cedula;
			}
			set
			{
				if ((this._cedula != value))
				{
					this._cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido1", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string apellido1
		{
			get
			{
				return this._apellido1;
			}
			set
			{
				if ((this._apellido1 != value))
				{
					this._apellido1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido2", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string apellido2
		{
			get
			{
				return this._apellido2;
			}
			set
			{
				if ((this._apellido2 != value))
				{
					this._apellido2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_provincia", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string provincia
		{
			get
			{
				return this._provincia;
			}
			set
			{
				if ((this._provincia != value))
				{
					this._provincia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_canton", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string canton
		{
			get
			{
				return this._canton;
			}
			set
			{
				if ((this._canton != value))
				{
					this._canton = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_distrito", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string distrito
		{
			get
			{
				return this._distrito;
			}
			set
			{
				if ((this._distrito != value))
				{
					this._distrito = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaNacimiento", DbType="VarChar(30)")]
		public string fechaNacimiento
		{
			get
			{
				return this._fechaNacimiento;
			}
			set
			{
				if ((this._fechaNacimiento != value))
				{
					this._fechaNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcionPaciente", DbType="VarChar(250)")]
		public string descripcionPaciente
		{
			get
			{
				return this._descripcionPaciente;
			}
			set
			{
				if ((this._descripcionPaciente != value))
				{
					this._descripcionPaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoPaciente", DbType="Int NOT NULL")]
		public int idTipoPaciente
		{
			get
			{
				return this._idTipoPaciente;
			}
			set
			{
				if ((this._idTipoPaciente != value))
				{
					this._idTipoPaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idInstitucion", DbType="Int NOT NULL")]
		public int idInstitucion
		{
			get
			{
				return this._idInstitucion;
			}
			set
			{
				if ((this._idInstitucion != value))
				{
					this._idInstitucion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcionExpediente", DbType="VarChar(350) NOT NULL", CanBeNull=false)]
		public string descripcionExpediente
		{
			get
			{
				return this._descripcionExpediente;
			}
			set
			{
				if ((this._descripcionExpediente != value))
				{
					this._descripcionExpediente = value;
				}
			}
		}
	}
	
	public partial class consultaSesionesResult
	{
		
		private int _idSesion;
		
		private string _asunto;
		
		private string _fecha;
		
		private string _hora;
		
		private string _notas;
		
		private string _sintomas;
		
		private int _idExpediente;
		
		private int _idUsuario;
		
		private string _color;
		
		public consultaSesionesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSesion", DbType="Int NOT NULL")]
		public int idSesion
		{
			get
			{
				return this._idSesion;
			}
			set
			{
				if ((this._idSesion != value))
				{
					this._idSesion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_asunto", DbType="VarChar(55)")]
		public string asunto
		{
			get
			{
				return this._asunto;
			}
			set
			{
				if ((this._asunto != value))
				{
					this._asunto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="VarChar(30)")]
		public string fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this._fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora", DbType="VarChar(7)")]
		public string hora
		{
			get
			{
				return this._hora;
			}
			set
			{
				if ((this._hora != value))
				{
					this._hora = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notas", DbType="VarChar(255)")]
		public string notas
		{
			get
			{
				return this._notas;
			}
			set
			{
				if ((this._notas != value))
				{
					this._notas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sintomas", DbType="VarChar(255)")]
		public string sintomas
		{
			get
			{
				return this._sintomas;
			}
			set
			{
				if ((this._sintomas != value))
				{
					this._sintomas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idExpediente", DbType="Int NOT NULL")]
		public int idExpediente
		{
			get
			{
				return this._idExpediente;
			}
			set
			{
				if ((this._idExpediente != value))
				{
					this._idExpediente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL")]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this._idUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string color
		{
			get
			{
				return this._color;
			}
			set
			{
				if ((this._color != value))
				{
					this._color = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
