#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Sylom")]
	public partial class LQProcesosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public LQProcesosDataContext() : 
				base(global::DAL.Properties.Settings.Default.SylomConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public LQProcesosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LQProcesosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LQProcesosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LQProcesosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.agregarPaciente")]
		public int agregarPaciente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string apellido1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string apellido2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string direccion2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1)")] string provincia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2)")] string canton, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(3)")] string distrito, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> genero, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string fechaNacimiento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(250)")] string descripcionCliente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTipoPaciente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idInstitucion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(350)")] string descripcionExpediente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula, nombre, apellido1, apellido2, direccion2, provincia, canton, distrito, genero, fechaNacimiento, descripcionCliente, idTipoPaciente, idInstitucion, descripcionExpediente);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eliminarPaciente")]
		public int eliminarPaciente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPaciente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPaciente);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.actualizarPaciente")]
		public int actualizarPaciente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPaciente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string apellido1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string apellido2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string direccion2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1)")] string provincia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2)")] string canton, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(3)")] string distrito, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> genero, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string fechaNacimiento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(250)")] string descripcionCliente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTipoPaciente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idInstitucion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(350)")] string descripcionExpediente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPaciente, cedula, nombre, apellido1, apellido2, direccion2, provincia, canton, distrito, genero, fechaNacimiento, descripcionCliente, idTipoPaciente, idInstitucion, descripcionExpediente);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.obtenerPacientes")]
		public ISingleResult<obtenerPacientesResult> obtenerPacientes()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<obtenerPacientesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.obtenerPaciente")]
		public ISingleResult<obtenerPacienteResult> obtenerPaciente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPaciente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPaciente);
			return ((ISingleResult<obtenerPacienteResult>)(result.ReturnValue));
		}
	}
	
	public partial class obtenerPacientesResult
	{
		
		private int _idPaciente;
		
		private string _cedula;
		
		private string _nombre;
		
		private string _apellido1;
		
		private string _apellido2;
		
		private string _provincia;
		
		private string _canton;
		
		private string _distrito;
		
		private string _fechaNacimiento;
		
		private string _descripcionPaciente;
		
		private int _idTipoPaciente;
		
		private int _idInstitucion;
		
		private string _descripcionExpediente;
		
		public obtenerPacientesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPaciente", DbType="Int NOT NULL")]
		public int idPaciente
		{
			get
			{
				return this._idPaciente;
			}
			set
			{
				if ((this._idPaciente != value))
				{
					this._idPaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string cedula
		{
			get
			{
				return this._cedula;
			}
			set
			{
				if ((this._cedula != value))
				{
					this._cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido1", DbType="VarChar(30)")]
		public string apellido1
		{
			get
			{
				return this._apellido1;
			}
			set
			{
				if ((this._apellido1 != value))
				{
					this._apellido1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido2", DbType="VarChar(30)")]
		public string apellido2
		{
			get
			{
				return this._apellido2;
			}
			set
			{
				if ((this._apellido2 != value))
				{
					this._apellido2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_provincia", DbType="VarChar(1)")]
		public string provincia
		{
			get
			{
				return this._provincia;
			}
			set
			{
				if ((this._provincia != value))
				{
					this._provincia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_canton", DbType="VarChar(2)")]
		public string canton
		{
			get
			{
				return this._canton;
			}
			set
			{
				if ((this._canton != value))
				{
					this._canton = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_distrito", DbType="VarChar(3)")]
		public string distrito
		{
			get
			{
				return this._distrito;
			}
			set
			{
				if ((this._distrito != value))
				{
					this._distrito = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaNacimiento", DbType="VarChar(30)")]
		public string fechaNacimiento
		{
			get
			{
				return this._fechaNacimiento;
			}
			set
			{
				if ((this._fechaNacimiento != value))
				{
					this._fechaNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcionPaciente", DbType="VarChar(250)")]
		public string descripcionPaciente
		{
			get
			{
				return this._descripcionPaciente;
			}
			set
			{
				if ((this._descripcionPaciente != value))
				{
					this._descripcionPaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoPaciente", DbType="Int NOT NULL")]
		public int idTipoPaciente
		{
			get
			{
				return this._idTipoPaciente;
			}
			set
			{
				if ((this._idTipoPaciente != value))
				{
					this._idTipoPaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idInstitucion", DbType="Int NOT NULL")]
		public int idInstitucion
		{
			get
			{
				return this._idInstitucion;
			}
			set
			{
				if ((this._idInstitucion != value))
				{
					this._idInstitucion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcionExpediente", DbType="VarChar(350) NOT NULL", CanBeNull=false)]
		public string descripcionExpediente
		{
			get
			{
				return this._descripcionExpediente;
			}
			set
			{
				if ((this._descripcionExpediente != value))
				{
					this._descripcionExpediente = value;
				}
			}
		}
	}
	
	public partial class obtenerPacienteResult
	{
		
		private int _idPaciente;
		
		private string _cedula;
		
		private string _nombre;
		
		private string _apellido1;
		
		private string _apellido2;
		
		private string _provincia;
		
		private string _canton;
		
		private string _distrito;
		
		private string _fechaNacimiento;
		
		private string _descripcionPaciente;
		
		private int _idTipoPaciente;
		
		private int _idInstitucion;
		
		private string _descripcionExpediente;
		
		public obtenerPacienteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPaciente", DbType="Int NOT NULL")]
		public int idPaciente
		{
			get
			{
				return this._idPaciente;
			}
			set
			{
				if ((this._idPaciente != value))
				{
					this._idPaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string cedula
		{
			get
			{
				return this._cedula;
			}
			set
			{
				if ((this._cedula != value))
				{
					this._cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido1", DbType="VarChar(30)")]
		public string apellido1
		{
			get
			{
				return this._apellido1;
			}
			set
			{
				if ((this._apellido1 != value))
				{
					this._apellido1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido2", DbType="VarChar(30)")]
		public string apellido2
		{
			get
			{
				return this._apellido2;
			}
			set
			{
				if ((this._apellido2 != value))
				{
					this._apellido2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_provincia", DbType="VarChar(1)")]
		public string provincia
		{
			get
			{
				return this._provincia;
			}
			set
			{
				if ((this._provincia != value))
				{
					this._provincia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_canton", DbType="VarChar(2)")]
		public string canton
		{
			get
			{
				return this._canton;
			}
			set
			{
				if ((this._canton != value))
				{
					this._canton = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_distrito", DbType="VarChar(3)")]
		public string distrito
		{
			get
			{
				return this._distrito;
			}
			set
			{
				if ((this._distrito != value))
				{
					this._distrito = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaNacimiento", DbType="VarChar(30)")]
		public string fechaNacimiento
		{
			get
			{
				return this._fechaNacimiento;
			}
			set
			{
				if ((this._fechaNacimiento != value))
				{
					this._fechaNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcionPaciente", DbType="VarChar(250)")]
		public string descripcionPaciente
		{
			get
			{
				return this._descripcionPaciente;
			}
			set
			{
				if ((this._descripcionPaciente != value))
				{
					this._descripcionPaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoPaciente", DbType="Int NOT NULL")]
		public int idTipoPaciente
		{
			get
			{
				return this._idTipoPaciente;
			}
			set
			{
				if ((this._idTipoPaciente != value))
				{
					this._idTipoPaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idInstitucion", DbType="Int NOT NULL")]
		public int idInstitucion
		{
			get
			{
				return this._idInstitucion;
			}
			set
			{
				if ((this._idInstitucion != value))
				{
					this._idInstitucion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcionExpediente", DbType="VarChar(350) NOT NULL", CanBeNull=false)]
		public string descripcionExpediente
		{
			get
			{
				return this._descripcionExpediente;
			}
			set
			{
				if ((this._descripcionExpediente != value))
				{
					this._descripcionExpediente = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
